### ISSUE TITLE
[Feature Request] Updating brick firmware

### ISSUE THREAD

**Issue by JakubVanek** [c4ev3/ev3duder#16]
Hi,

I think it is sometimes useful to have the ability to upload a new firmware to the brick. So far on Linux this has been provided by the [C# firmware loader](https://github.com/ev3dev/lms-hacker-tools/tree/master/PBrickTools/Ev3FirmwareLoader.Cli). I have written a different tool for my need, but I think it would be nice to have this in ev3duder too.

I believe the builtin EV3 EEPROM is responsible for handling the upload. The write protect pin is permanently activated, so I think it is not possible to hard-brick the brick this way.

I don't know from where the protocol originates. I think it comes from BricxCC and it is not publicly documented. However it is very similar to the protocol that the LMS2012 VM uses when it is running. It is using system commands too, but it is using different command IDs.

The upload has four phases:
 * The bootloader is asked to erase the flash chip (this is optionally handled together with the following step).
 * The firmware binary is uploaded to the bootloader similarly to how normal files are uploaded (begin & continue requests).
 * The bootloader is asked to produce a checksum of the newly uploaded data.
 * The bootloader is then asked to do a reboot to the new system.

There are two more commands:
 * It is possible to ask the bootloader about its version and the hardware version (both are V0.60 on my brick).
 * It is possible to ask the running Linux system to reboot into the bootloader quickly without saving any data.

It may be even possible do partial uploads that would preserve user data by not erasing the whole chip. However I have not yet tested this. The remaining functionality is tested to work.

I have the following proposal for the interface:
```
# Exit Linux and enter firmware upload mode
ev3 flash enter

# Upload the firmware
# - either performing all the steps or only the upload phase (advanced)
# - optionally upload from address n to address n+len(@file.img)
# - optionally select flash erase mode
ev3 flash upload <file.img> [--only] [--start n] [--erase-mode=separate/merged]

# Erase the entire flash contents (= separate flash erasure)
ev3 flash erase

# Ask the bootloader for flash CRC32
ev3 flash crc32 <start> <end>

# Show information about the bootloader
ev3 flash info

# Exit the bootloader
ev3 flash exit
```

Best regards,

Jakub

**Comment by a3f** [comment]
Just to be sure: you can't overwrite the bootloader that way, right?

**Comment by JakubVanek** [comment]
Yes, this bootloader is stored in a separate chip that cannot be written via USB (as far as I know). There's uboot in the main flash image, but it is chainloaded from the EEPROM.

However, I have noticed that the EEPROM containing it is *not* write protected (WP is tied low, for some reason I thought it was tied high). This means that it could be possible to reprogram the EEPROM from booted Linux.
![eeprom](https://user-images.githubusercontent.com/6003171/91668533-aa26e780-eb0d-11ea-8a33-ad7193fbaecf.png)
