### ISSUE TITLE
[Feature Request] Direct bytecode execution

### ISSUE THREAD

**Issue by JakubVanek** [c4ev3/ev3duder#17]
Hi,

this is hopefully my last feature request :D 
I think it would be nice to have a way of sending direct commands to the brick. Currently only selected commands are supported. This would expand the scope to all commands available.

The direct command request encoding is quite simple:
https://github.com/JakubVanek/ev3tool/blob/37582e398df192ef4078946877e03e253f707d80/libcomm/src/ev3loader/commands/direct/execute.cpp#L18

Therefore I'd propose the following interface:
```
ev3 directcmd <number of locals> \
              <number of globals> \
              <source file with bytecode or - for stdin> \
              <destination file for globals or - for stdout> \
              [--noreply]
```

Best regards,

Jakub

**Comment by a3f** [comment]
Needless to say, if you submit a pull request, it'll most likely be accepted. So go for it if you like ^^

**Comment by JakubVanek** [comment]
Thank you, I have opened #26 that should address this.
