### ISSUE TITLE
Eclipse Neon 2.0 cpp EV3duder couldn't be found in !

### ISSUE THREAD

**Issue by Paul330** [c4ev3/ev3duder#2]
Hello I am pretty new to this topic and Eclipse and I hope you can help or know someone who can support me. I installed Eclipse Neon 2.0 cpp and wanted to test the EV3 "Hello World". But when I try to upload and run the programm I always get a message Uploader not found "Ev3duder couldn't be found in ! 
When I press OK, I get the message `The project's uploader path <> is invalid`. Try correcting it. But how?

When I start a new project I define the path with `C:\ev3\uploader` as it is installed automatically. But when I open project\properties\C/C++ Build\Setting\Toolchains --> The line EV3 Uploader (ev3duder) is empty. I tried to use the browse button and copied the path from the explorer but when I Apply and press OK the failure still remains. When I go back to the settings the EV3 Uploader is still empty.

I trying to program my EV3 with the c4EV3 since some weeks but still have problems. As I already wrote I am new to Eclipse and if you would have some more documentation or a workaround it would be a great help.

KR Paul

**Comment by a3f** [comment]
Hello there,

do you've a `C:\ev3\uploader\ev3duder.exe` program on your system?
If so, I'd like to ask you to copy your issue and repost it in https://github.com/c4ev3/EV3-Eclipse-Plugin for better visibility, if someone runs into the same problem. I'll get notified when you do.

A couple of weeks is quite some time, you didn't need to wait that long =)

Best regards,

**Comment by Paul330** [comment]
Hi,

yeah I have the ev3duder.exe. I will switch my issue to the other topic.

Some weeks because I had some other Eclipse setting problems, two kids and
some other business so not much time for my EV3. But finally I want to
program my brick with c++. :-)

Mit freundlichen Grüßen
Paul Halbmayr

Am 15.04.2017 1:43 nachm. schrieb "Ahmad Fatoum" <notifications@github.com>:

**Comment by a3f** [comment]
Heh, two more young c4ev3 users. We better get this working then. ^^

I'll close this issue, so we can continue over there.

**Comment by Paul330** [comment]
Hopefully. But I am afraid we will have some more time. (3 and 5 years
old).

I think it shouldn't be a big problem. Not sure why I can't overwrite the
path.

Do you have an example program I can try?

Mit freundlichen Grüßen
Paul Halbmayr

Am 15.04.2017 2:26 nachm. schrieb "Ahmad Fatoum" <notifications@github.com>:

**Comment by a3f** [comment]
You didn't choose the "Hello World EV3 C++ Project" option?

**Comment by Paul330** [comment]
Yes I chose it. Does it incl. All settings? E. g. it was missing the string
include header so I added the MinGW Includes and then it worked.

But maybe it's only a problem caused by my missing Eclipse skills. But c++
with mingw works fine.

Mit freundlichen Grüßen
Paul Halbmayr

Am 15.04.2017 2:31 nachm. schrieb "Ahmad Fatoum" <notifications@github.com>:
