### ISSUE TITLE
Bluetooth Problem

### ISSUE THREAD

**Issue by fugiro** [c4ev3/ev3duder#4]
Hi there. 

I'm using C4EV3 on Windows 10 and its working fine via USB. Thanks again for this nice piece of software.

I'm now facing troubles to upload the code via ev3duder. 

1) If the project is configured to use the SD Card, the resulting program is uploaded to the media card and can be re-used anytime. However, when the project is configured to use the EV3 Brick Internal Memmory, after the the firs run (clicking on Upload and Run), the desappear from the brick.

2) I'm also trying to upload via bluetooh, from inside the Eclipse IDE. After pairing the device, a virtual comport is created. However, I wasn't able to configure it and upload the program. 

Can I have some tips on these topics? Thanks again.

**Comment by a3f** [comment]
Glad you like it.

1. Does it work the first time? Do I understand you correctly that the problem is that no menu entry is created?
2. EV3 Menu ➜ Connection settings ➜ Set Bluetooth COM Port

**Comment by a3f** [comment]
I'll close this issue, because of inactivity.
