### ISSUE TITLE
Upload sd-card data from ev3 to pc

### ISSUE THREAD

**Issue by thodec95** [c4ev3/ev3duder#44]
Hello everyone,

is there any way to upload data from the SD-card without taking it out of the ev3? 
I wrote a program that creates a text file and saves it on the SD-card. Now I want to analyze the data but I dont want to take it out each time I've changed something.

**Comment by thodec95** [comment]
I want to use USB connection for the transfer. No Bluetooth and no Wifi.

**Comment by a3f** [comment]
Try something like:
```
$ ev3duder dl /media/card/mylog.txt
```

**Comment by thodec95** [comment]
I tried to download the ev3duder.exe but I cant open it. I can see a loading screen for 1 second and then it closes automatically.

**Comment by a3f** [comment]
Run above line from Windows Terminal and paste here any error output you may see.

**Comment by thodec95** [comment]
Now I got it. Thank you it works!
